config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'
  get '/portfolio' => 'pages#portfolio'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rebecca Kleinberg</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,500,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= favicon_link_tag 'cheops.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div class="container">
    <div class="name col-lg-6">
      <h1><%= link_to_unless_current "Rebecca Kleinberg", root_path %></h1>
    </div>
    <div class="header-menu col-lg-6">
      <ul>
        <li><=% link_to "About", about_path %></li>
        <li><%= link_to "Portfolio", portfolio_path %></li>
        <li>Contact</li>
      </ul>
    </div>
  </div> <%# container %>
</div> <%# header %>
<%= yield %>
<div class="footer">
  <div class="container">
    <div class="footer-menu">
      <ul>
        <li><%= link_to(image_tag("github.png", title: "github"), "https://github.com/RebeccaKleinberg") %></li>
        <li><%= link_to(image_tag("twitter.png", title: "twitter"), "https://twitter.com/Rebecca_BK") %></li>
        <li><%= link_to(image_tag("linkedin.png", title: "linkedin"), "https://www.linkedin.com/in/rebeccakleinberg") %></li>
      </ul>
    </div>
  </div>
</div> <%# footer %>
</body>
</html>

app/views/pages/portfolio.html.erb
<div class="main">
  <ul>
    <li><%= link_to(image_tag("", title: ""), "") %></li>
    <li><%= link_to(image_tag("juke.png", title: "Juke"), "jukeapp.herokuapp.com") %></li>
    <li><%= link_to(image_tag("", title: ""), "") %></li>
  </ul>
</div>

app/views/pages/welcome.html.erb
<div class="main home">
  <div class="jumbotron">
    <div class="container cheops">
      <%= image_tag "cheops.jpg" %>
    </div> <%# container %>
  </div> <%# jumbotron %>
</div> <%# main home %>